set -o vi

#PS1="\u@\h:\[\e[1;36m\]\w\[\e[0m\]\$ "
PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;36m\]\w\[\033[00m\]\$ "

#LS_COLORS=$LS_COLORS:'di=1;34:ln=1;36'; export LS_COLORS;
LS_COLORS=$LS_COLORS:'di=1;36:ln=1;31'; export LS_COLORS;

alias rm='rm -i'
alias repo='cd $HOME/repos'
alias repos='cd $HOME/repos'
