---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: myapp 
  name: nginx1 
spec:
  volumes:
    - name: hostpath-vol
      persistentVolumeClaim:
        claimName: test-dynamic-volume-claim
  containers:
    - image: nginx
      name: myapp
      resources: {}
      volumeMounts:
        - name: hostpath-vol
          mountPath: /root/hostpath-mount-point
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
